name: Publish

on:
  push:
    tags: ["v*"]

jobs:
  test:
    uses: ./.github/workflows/test.yaml

  publish-npm:
    needs: test
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v4

      - uses: oven-sh/setup-bun@v2

      - run: bun install

      - run: bun publish --access public
        env:
          NPM_CONFIG_TOKEN: ${{ secrets.NPM_TOKEN }}
